services:
  web:
    build: .
    volumes:
      - .:/api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://root:mdp@db/game_db
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
